title: "(Kindle版)【完全版】In silico創薬実践書 〜おうち創薬で論文を書こう〜"
summary: |-
  📰 概要
  in silico創薬の技術を網羅的に知りたい方、さらにそれらを用いてPCだけで論文を書きたい方へ。

  本書は、wetラボでの創薬研究の経験を持つバイオインフォマティシャンである著者が、実際の論文を基に、in silico創薬の手法について解説した技術書です。一番厄介な環境構築から具体的な使用方法、エラーの対処法までを丁寧に説明しております。

  本技術書で紹介されている手法はここ10年で数多くの論文で紹介される最新の手法であり、本手法を用いて、論文化も可能です。

  本書を通して、in silico創薬を学び、論文化までしてみませんか？

  👫 対象とする読者
  ・in silico創薬で論文を執筆したい方
  ・in silico創薬の各手法を研究に活かしたい方
  ・PCだけで論文を書きたい方
  ・in silico創薬の手法を網羅的に使えるようになりたい方

  本技術書は随時アップデートされていきます。
  一度購入された方はアップデートされたとしても追加料金は発生しませんのでご安心ください。

  📰アップデート情報
  2025/01/09: リリースしました！
  2025/02/27: 微修正
  2025/03/30: Homology Modelingの章を追加
  2025/04/06: 化合物ライブラリの章を追加
  2025/04/13: RDKitを用いた化合物フィルタリングの章を追加
  2025/04/20: sminaを用いたin silico screeningの章を追加、GROMACSのMac版の環境構築方法を追加
  2025/05/02: タンパク質-リガンド相互作用の可視化の章を追加
  2025/05/07: お客様の声追加
  2025/05/31: 全体の修正
  2025/06/08: MDの章を修正、タンパク質の安定化の章追加
  2025/08/20: OpenMMを使ったエネルギー最小化、Pymolを使ったGrid box作成追加、全体の微修正
  2025/09/24: MDの環境構築修正
  2026/01/06: MM-PBSA/GBSAの章、Waterswappingの章に注意書きを追加
  2026/03/12: Kindle用に全体の構成修正

  📣お知らせ
  2025/08/26: ケモインフォマティクス若手の会で、in silico創薬のレクチャーを行いました。
  2025/11/12: 本書で解説・検証している技術を活用した、新たな研究論文がMolecules誌に掲載されました！🎉🎉🎉
  https://www.mdpi.com/1420-3049/30/22/4370
  2026/02/01: 本書がChiral社(https://x.com/chiralscience)が協賛するコンペの推薦図書となりました！
  期間限定で該当の分子ドッキングのパートを無料公開しています。

topics:
  - "バイオインフォマティクス"
  - "Insilico創薬"
  - "インシリコ創薬"
  - "おうち創薬"
  - "labcode"
published: false
price: 2800
toc_depth: 2
allow_override: true
chapters:
  - "1z4dau"
  - "2z4dau"
  - "3z4dau"
  - "3z4dau-1"
  - "3z4dau-2"
  - "3z4dau-3"
  # 第1章：ターゲット準備
  - "4z4dau"
  - "4z4dau-1"
  - "4z4dau-2"
  - "4z4dau-3"
  # 第2章：Homology modeling
  - "14z4da"
  - "14z4da-1"
  - "14z4da-2"
  - "14z4da-3"
  # 第3章：化合物ライブラリまとめ
  - "15z4da"
  - "15z4da-1"
  - "15z4da-2"
  - "15z4da-3"
  - "15z4da-4"
  - "15z4da-5"
  - "15z4da-6"
  - "15z4da-7"
  # 第4章：RDKitフィルタリング
  - "16z4da"
  - "16z4da-1"
  - "16z4da-2"
  - "16z4da-3"
  # 第5章：In silico screening
  - "6z4dau"
  - "6z4dau-1"
  - "6z4dau-2"
  - "6z4dau-3"
  # 第6章：Sminaスクリーニング
  - "17z4da"
  - "17z4da-1"
  - "17z4da-2"
  - "17z4da-3"
  - "17z4da-4"
  - "17z4da-5"
  - "17z4da-6"
  - "17z4da-7"
  - "17z4da-8"
  # 第7章：タンパク質-リガンド相互作用可視化
  - "18z4da"
  - "18z4da-1"
  - "18z4da-2"
  - "18z4da-3"
  - "18z4da-4"
  - "18z4da-5"
  - "18z4da-6"
  # 第8章：MD simulation環境構築
  - "7z4dau"
  - "7z4dau-1"
  - "7z4dau-2"
  - "7z4dau-3"
  # 第9章：MDタンパク質安定化
  - "20z4da"
  - "20z4da-1"
  - "20z4da-2"
  - "20z4da-3"
  - "20z4da-4"
  - "20z4da-5"
  - "20z4da-6"
  - "20z4da-7"
  - "20z4da-8"
  - "20z4da-9"
  - "20z4da-10"
  # 第10章：リガンド-タンパク質 MD simulation
  - "8z4dau"
  - "8z4dau-1"
  - "8z4dau-2"
  - "8z4dau-3"
  - "8z4dau-4"
  - "8z4dau-5"
  - "8z4dau-6"
  - "8z4dau-7"
  - "8z4dau-8"
  - "8z4dau-9"
  - "8z4dau-10"
  # 第11章：RMSD, RMSF, RoG, hydrogen bond, RDF解析
  - "9z4dau"
  - "9z4dau-1"
  - "9z4dau-2"
  - "9z4dau-3"
  - "9z4dau-4"
  - "9z4dau-5"
  - "9z4dau-6"
  # 第12章：MM-GBSA/PBSA
  - "10z4da"
  - "10z4da-1"
  - "10z4da-2"
  - "10z4da-3"
  - "10z4da-4"
  - "10z4da-5"
  # 第13章：Water swapping
  - "11z4da"
  - "11z4da-1"
  - "11z4da-2"
  - "11z4da-3"
  - "11z4da-4"
  - "11z4da-5"
  # 第14章：物性評価
  - "12z4da"
  - "12z4da-1"
  - "12z4da-2"
  - "12z4da-3"
  # あとがき
  - "13z4da"
  - "13z4da-1"
